dockerConfig: "docker_config.yaml"
exps:
  - type: "micro" #name of the exp
    name: "performance"
    duration: 120

    #    tcSetup: [ "tc_1.yaml","tc_2.yaml", "tc_3.yaml" ]
    tcSetup: [ "tc_1.yaml", "tc_2.yaml", "tc_3.yaml" ]
    #    nodes: [1, 20, 200]
    nodes: [ 1,20,200 ]
    #    dataDistribution: ["global", "local"]
    dataDistribution: [ "global", "local" ]
    #    readPercents: [95, 50, 0]
    readPercents: [ 0, 50, 95 ]
    #    threads: [ 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048 ]
    threads: [ 4, 8, 16, 32, 64, 128, 192, 256, 384, 512, 768, 1024]

    threadLimit:
      1:
        global:
          0: 384
          50: 384
          95: 384
        local:
          0: 384
          50: 384
          95: 384
      20:
        global:
          0: 192
          50: 192
          95: 768
        local:
          0: 192
          50: 512
          95: 1024
      200:
        global:
          0: 192
          50: 192
          95: 768
        local:
          0: 192
          50: 384
          95: 1024

    partitions:
      0: "A"
      1: "B"
      2: "C"
      3: "D"
      4: "E"
      5: "F"
      6: "G"
      7: "H"
