dockerConfig: "docker_config.yaml"
exps:
  - type: "micro" #name of the exp
    name: "performance"
    skip: false
    duration: 120
    #    tcSetup: [ "tc_1.yaml","tc_2.yaml", "tc_3.yaml" ]
    tcSetup: [ "tc_1.yaml" ]
    #    nodes: [1, 50, 100, 300]
    nodes: [ 1, 50, 100, 300 ]
    #    threads: [ 1, 2, 4, 8, 16, 32, 64, 128, 256, 512 ]
    threads: [ 1,2,4,8 ]
    #    readPercents: [95, 50, 0]
    readPercents: [ 95, 50,0 ]
    #    dataDistribution: ["global", "local", "distance"]
    dataDistribution: [ local, global ]
    partitions:
      0: "A"
      1: "B"
      2: "C"
      3: "D"
      4: "E"
      5: "F"
      6: "G"
      7: "H"

#  - type: "micro_failures"
#    name: "failures"
#    skip: true
#    tcSetup: [ "tc_1.yaml","tc_2.yaml", "tc_3.yaml" ]
#    nodes: [1, 50, 100, 300]
#    duration: 120
#    dataDistribution: ["global", "local", "distance"]


