dockerConfig: "docker_config.yaml"
exps:
  - type: "migration" #name of the exp
    name: "migration"

    duration: 90
    migrateAt: 40

    #    tcSetup: [ "tc_1.yaml","tc_2.yaml", "tc_3.yaml" ]
    tcSetup: [ "tc_1.yaml"]
    #    nodes: [1, 50, 100, 300]
    nodes: [ 200 ]
    #    threads: [ 1, 2, 4, 8, 16, 32, 64, 128, 256, 512 ]
    # threads: 16
    threads: 16
    limit: 100

    #    readPercents: [95, 50, 0]
    readPercents: [ 95 ]
    dataDistribution: [ "local" ]

    migrationPattern: ["random", "commute"]


    gcThreshold: 1000
    gcPeriod: 1000

    partitions:
      0: "A"
      1: "B"
      2: "C"
      3: "D"
      4: "E"
      5: "F"
      6: "G"
      7: "H"
