## setup information
setup:

  nContainers: 300
  maxContainersPerMachine: 50
  imageLoc: "/home/pfouto/edge/exps/docker/tc.tar"
  imageTag: "tc:0.1"

  nodeLocationsFile: "/home/pfouto/edge/exps/configs/node_locations_300.txt"

  logsFolder: "/home/pfouto/edge/logs"
  codeFolder: "/home/pfouto/edge/deploy"
  tcFolder: "/home/pfouto/edge/exps/tc"


  latencyFile: "latencies_300.txt"

  networkName: "edgenet"
  subnet: "10.10.0.0/16" #docker network ip range
  gateway: "10.10.0.1" #docker network gateway

## exp information
exps:
  - name: "static_test" #name of the exp
    type: "basic"
    skip: false
    nodes:
      eu: 300
    duration: 70 #duration of the experiment
    #staticTree: "tree/treegpt.yaml"

  - name: "regular" #name of the exp
    type: "basic"
    skip: true
    nodes:
      as: 10
      eu: 10
      na: 10
      oce: 10
      sa: 10
    duration: 40 #duration of the experiment

  - name: "dying" #name of the exp
    type: "dying"
    skip: true
    nodes:
      as: 10
      eu: 10
      na: 10
      oce: 10
      sa: 10

    steps:
      - delay: 40
        kill:
          as: [2,4,6]
          eu: [3,5,7]
          na: [4, 8, 9]
      - delay: 15
        kill:
          oce: [2]
          sa: [3]
          na: [1]
      - delay: 15

  - name: "dying_single" #name of the exp
    type: "dying"
    skip: true
    staticTree: "tree/treegpt.yaml"
    nodes:
      eu: 50

    steps:
      - delay: 40
        kill:
          eu: [3,5,7, 12, 15, 25, 30, 35, 40, 45]
      - delay: 20
        kill:
          eu: [1, 8, 10, 18, 22, 28, 32, 38, 42, 48]
      - delay: 20
