dockerConfig: "cass_docker_config.yaml"
exps:
  - type: "cassandra" #name of the exp
    name: "cassandra"

    tcSetup: [ "tc_1.yaml"]
    #    nodes: [1, 20, 200]
    nodes: [ 20 ]

    dataDistribution: [ "local", "global" ]

    duration: 120

    partitions:
      0: "a"
      1: "b"
      2: "c"
      3: "d"
      4: "e"
      5: "f"
      6: "g"
      7: "h"
