dockerConfig: "cass_docker_config.yaml"
exps:
  - type: "micro_cassandra" #name of the exp
    name: "micro_cassandra"
    duration: 120

    tcSetup: [ "tc_1.yaml", "tc_2.yaml", "tc_3.yaml"]
    #    nodes: [1, 20, 200]
    nodes: [ 1, 20, 200 ]

    dataDistribution: [ "local" ]

    readPercents: [ 0, 50, 95, 100 ]
    threads: [ 2, 4, 8, 16, 32, 64, 128, 192, 256, 384, 512, 768, 1024 ]

    threadLimit:
      1:
        global:
          0: 512
          50: 256
          95: 512
          100: 768
        local:
          0: 512
          50: 256
          95: 384
          100: 768
      20:
        global:
          0: 64
          50: 64
          95: 64
          100: 128
        local:
          0: 128
          50: 64
          95: 128
          100: 256
      200:
        global:
          0: 16
          50: 8
          95: 32
          100: 256
        local:
          0: 32
          50: 16
          95: 32
          100: 256

    partitions:
      0: "a"
      1: "b"
      2: "c"
      3: "d"
      4: "e"
      5: "f"
      6: "g"
      7: "h"
