dockerConfig: "cass_docker_config.yaml"
exps:
  - type: "micro_cassandra" #name of the exp
    name: "micro_cassandra"
    duration: 120

    tcSetup: [ "tc_1.yaml", "tc_2.yaml", "tc_3.yaml"]
    #    nodes: [1, 20, 200]
    nodes: [ 20, 200 ]

    dataDistribution: [ "local" ]

    readPercents: [ 0, 50, 95, 99, 100 ]
    threads: [ 2, 4, 8, 16, 32, 64, 128, 192, 256 ]

    threadLimit:
      20:
        local:
          0: 192
          50: 192
          95: 192
          99: 256
          100: 256
      200:
        local:
          0: 192
          50: 128
          95: 192
          99: 256
          100: 256

    partitions:
      0: "a"
      1: "b"
      2: "c"
      3: "d"
      4: "e"
      5: "f"
      6: "g"
      7: "h"
